version: '3.7'

services:
    caddy:
        image: horizontalscaling/caddy
        ports:
            - 80:80
            - 443:443
        # Add reverse_proxy as attached network.
        networks:
            - reverse_proxy
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"
        networks:
            - reverse_proxy
    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - reverse_proxy
    auth:
        image: horizontalscaling/auth
        ports:
            - "3000:3000"
        environment:
            - PORT=3000
            - DB_HOST=postgres
            - DB_USERNAME=postgres
            - DB_PORT=5432
            - DB_NAME=hscalingk8s
            - DB_PASSWORD=postgres
        networks:
            - reverse_proxy
        depends_on: 
            - postgres

networks:
  # Add reverse_proxy as an external network.
  reverse_proxy:
    driver: "bridge"